name: barberia
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  generate: true


