name: barberia
description: "Multi-platform barber shop booking app: browse services, select date & time, localized (es/en), reminders, themed & accessible UI."
publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  table_calendar: ^3.0.9
  flutter_markdown: ^0.7.3+1
  http: ^1.2.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  sqflite: ^2.3.0
  path: ^1.8.3
  add_2_calendar: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  generate: true


